{
 "title": "Ceph Cluster",
 "description": "Overview of your Ceph cluster.",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "CLUSTER STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ceph health status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_health_status{}" }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{}[5m]))"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{}[5m]))"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_cluster_total_bytes{}" }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ceph_cluster_total_bytes{}-ceph_cluster_total_used_bytes{})/ceph_cluster_total_bytes{}"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_pool_objects{})" }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    { "expr": "sum(ceph_osd_op_w_in_bytes{})" }
   ]
  },
  {
   "title": "Bytes Read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    { "expr": "sum(ceph_osd_op_r_out_bytes{})" }
   ]
  },
  {
   "title": "Alerts starting with Ceph",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",alertname=~\"^Ceph.+\"}) OR vector(0)"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w{}[5m]))"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_r{}[5m]))"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{}"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "expr": "sum(ceph_pool_objects)" }
   ]
  },
  {
   "title": "Mon Session Num",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_mon_num_sessions{})" }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_mon_quorum_status{}) or vector(0)"
    }
   ]
  },
  { "title": "OSD STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "OSDs OUT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{}) - count(ceph_osd_in{})"
    }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{} == 0.0) OR vector(0)"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_osd_up{})" }
   ]
  },
  {
   "title": "OSDs IN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_osd_in{})" }
   ]
  },
  {
   "title": "Avg PGs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(ceph_osd_numpg{})" }
   ]
  },
  {
   "title": "Avg Apply Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{})"
    }
   ]
  },
  {
   "title": "Avg Commit Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms{})"
    }
   ]
  },
  {
   "title": "Avg Op Write Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_w_latency_sum{}[5m]) / rate(ceph_osd_op_w_latency_count{}[5m]) >= 0)"
    }
   ]
  },
  {
   "title": "Avg Op Read Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_r_latency_sum{}[5m])/rate(ceph_osd_op_r_latency_count{}[5m]) >= 0)"
    }
   ]
  },
  { "title": "CLUSTER STATS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{}-ceph_cluster_total_used_bytes{}",
     "legendFormat": "Available"
    },
    {
     "expr": "ceph_cluster_total_used_bytes{}",
     "legendFormat": "Used"
    },
    { "expr": "ceph_cluster_total_bytes{}", "legendFormat": "Total Capacity" }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w{}[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r{}[5m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Cluster Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{}[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{}[5m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Pool Used Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ceph_pool_bytes_used{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool RAW Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ceph_pool_avail_raw{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
     "legendFormat": "{{name}} Avail"
    },
    {
     "expr": "(ceph_pool_stored_raw{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
     "legendFormat": "{{name}} Stored"
    }
   ]
  },
  {
   "title": "Objects Per Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(ceph_pool_objects{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Quota Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ceph_pool_quota_bytes{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Objects Quota",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(ceph_pool_quota_objects{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "OSD Type Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(ceph_bluestore_kv_commit_lat_count{})",
     "legendFormat": "BlueStore"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerts starting with Ceph",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ALERTS{alertstate=\"firing\",alertname=~\"^Ceph.+\"}"
      }
     ]
    },
    {
     "title": "Top Sluggish OSDs",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,sort_desc(ceph_osd_apply_latency_ms{} + ceph_osd_commit_latency_ms{}))",
       "legendFormat": "_auto"
      }
     ]
    },
    {
     "title": "Down OSDs",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "ceph_osd_up{} == 0" }
     ]
    }
   ]
  },
  {
   "title": "Node Statistics (NodeExporter)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Active_anon_bytes{}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(node_memory_Active_anon_bytes{})",
       "legendFormat": "Cluster Memory Usage"
      }
     ]
    },
    {
     "title": "Node CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by(instance)(irate(node_cpu_seconds_total{job='node',mode!=\"idle\"}[$interval])) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node Out",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_disk_read_bytes_total{}[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node In",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_disk_written_bytes_total{}[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Free Space in root filesystem",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_filesystem_free_bytes{ mountpoint=\"/\", device != \"rootfs\"})*100 / (node_filesystem_size_bytes{ mountpoint=\"/\", device != \"rootfs\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "OBJECTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "OSD Type Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(ceph_pool_objects)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "PGs State",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(ceph_pg_active{})", "legendFormat": "Active" },
    { "expr": "sum(ceph_pg_clean{})", "legendFormat": "Clean" },
    { "expr": "sum(ceph_pg_peering{})", "legendFormat": "Peering" },
    { "expr": "sum(ceph_pg_degraded{})", "legendFormat": "Degraded" },
    { "expr": "sum(ceph_pg_stale{})", "legendFormat": "Stale" },
    { "expr": "sum(ceph_unclean_pgs{})", "legendFormat": "Unclean" },
    { "expr": "sum(ceph_pg_undersized{})", "legendFormat": "Undersized" },
    { "expr": "sum(ceph_pg_incomplete{})", "legendFormat": "Incomplete" },
    { "expr": "sum(ceph_pg_forced_backfill{})", "legendFormat": "Forced Backfill" },
    { "expr": "sum(ceph_pg_forced_recovery{})", "legendFormat": "Forced Recovery" },
    { "expr": "sum(ceph_pg_creating{})", "legendFormat": "Creating" },
    { "expr": "sum(ceph_pg_wait_backfill{})", "legendFormat": "Wait Backfill" },
    { "expr": "sum(ceph_pg_deep{})", "legendFormat": "Deep" },
    { "expr": "sum(ceph_pg_scrubbing{})", "legendFormat": "Scrubbing" },
    { "expr": "sum(ceph_pg_recovering{})", "legendFormat": "Recovering" },
    { "expr": "sum(ceph_pg_repair{})", "legendFormat": "Repair" },
    { "expr": "sum(ceph_pg_down{})", "legendFormat": "Down" },
    { "expr": "sum(ceph_pg_peered{})", "legendFormat": "Peered" },
    { "expr": "sum(ceph_pg_backfill{})", "legendFormat": "Backfill" },
    { "expr": "sum(ceph_pg_remapped{})", "legendFormat": "Remapped" },
    {
     "expr": "sum(ceph_pg_backfill_toofull{})",
     "legendFormat": "Backfill Toofull"
    }
   ]
  },
  {
   "title": "Stuck PGs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(ceph_pg_degraded{})", "legendFormat": "Degraded" },
    { "expr": "sum(ceph_pg_stale{})", "legendFormat": "Stale" },
    { "expr": "sum(ceph_pg_undersized{})", "legendFormat": "Undersized" }
   ]
  },
  {
   "title": "Recovery Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_recovery_ops{}[$interval]))",
     "legendFormat": "OPS"
    }
   ]
  },
  { "title": "LATENCY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "OSD Apply Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    { "expr": "ceph_osd_apply_latency_ms{}" }
   ]
  },
  {
   "title": "OSD Commit Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    { "expr": "ceph_osd_commit_latency_ms{}" }
   ]
  },
  {
   "title": "OSD Read Op Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r_latency_sum{}[5m]) / rate(ceph_osd_op_r_latency_count{}[5m]) >= 0"
    }
   ]
  },
  {
   "title": "OSD Write Op Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_w_latency_sum{}[5m]) / rate(ceph_osd_op_w_latency_count{}[5m]) >= 0"
    }
   ]
  },
  {
   "title": "Recovery Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_r_latency_sum{}[5m]) / rate(ceph_osd_op_r_latency_count{}[5m]) >= 0)",
     "legendFormat": "Read"
    },
    {
     "expr": "avg(rate(ceph_osd_op_w_latency_sum{}[5m]) / rate(ceph_osd_op_w_latency_count{}[5m]) >= 0)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "AVG OSD Apply + Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{})",
     "legendFormat": "apply"
    },
    {
     "expr": "avg(ceph_osd_commit_latency_ms{})",
     "legendFormat": "commit"
    }
   ]
  },
  {
   "title": "Ceph Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ceph OSD Versions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_osd_metadata{})"
      }
     ]
    },
    {
     "title": "Ceph Mon Versions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_mon_metadata{})"
      }
     ]
    },
    {
     "title": "Ceph MDS Versions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_mds_metadata{})"
      }
     ]
    },
    {
     "title": "Ceph RGW Versions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_rgw_metadata{})"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Ceph - OSD (Single)",
 "description": "CEPH OSD Status.",
 "tags": [
  "ceph",
  "osd"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "osd",
    "label": "OSD",
    "query": {
     "query": "label_values(ceph_osd_up, ceph_daemon)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OSD Status / Total OSDs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (ceph_osd_up{ceph_daemon=\"$osd\"})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (ceph_osd_in{ceph_daemon=\"$osd\"})"
    }
   ]
  },
  {
   "title": "Total OSDs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count without (instance, ceph_daemon) (ceph_osd_up)"
    }
   ]
  },
  {
   "title": "OSD: $osd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PGs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_osd_numpg{ceph_daemon=~\"$osd\"})",
     "legendFormat": "Number of PGs"
    },
    {
     "expr": "avg without (instance, ceph_daemon) (ceph_osd_numpg)",
     "legendFormat": "Average Number of PGs in the Cluster"
    }
   ]
  },
  {
   "title": "OSD Storage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_osd_stat_bytes{ceph_daemon=\"osd.0\"}-ceph_osd_stat_bytes_used{ceph_daemon=\"osd.0\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_osd_stat_bytes_used{ceph_daemon=~\"$osd\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_osd_stat_bytes_used{ceph_daemon=\"osd.0\"}/ceph_osd_stat_bytes{ceph_daemon=\"osd.0\"})"
    }
   ]
  },
  {
   "title": "Latency, Storage, Utilization Varience",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OSD Apply Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum without (instance) (ceph_osd_apply_latency_ms{ceph_daemon='$osd'})"
    }
   ]
  },
  {
   "title": "OSD Commit Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum without (instance) (ceph_osd_commit_latency_ms{ceph_daemon='$osd'})"
    }
   ]
  },
  {
   "title": "OSD Read Op Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum without (instance) (rate(ceph_osd_op_r_latency_sum{ceph_daemon='$osd'}[5m]) / rate(ceph_osd_op_r_latency_count{ceph_daemon='$osd'}[5m]) >= 0)"
    }
   ]
  },
  {
   "title": "OSD Write Op Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum without (instance) (rate(ceph_osd_op_w_latency_sum{ceph_daemon='$osd'}[5m]) / rate(ceph_osd_op_w_latency_count{ceph_daemon='$osd'}[5m]) >= 0)"
    }
   ]
  },
  {
   "title": "Avg OSD  Op  Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg without (instance, ceph_daemon) (rate(ceph_osd_op_r_latency_sum{ceph_daemon='$osd'}[5m]) / rate(ceph_osd_op_r_latency_count{ceph_daemon='$osd'}[5m]) >= 0)",
     "legendFormat": "read"
    },
    {
     "expr": "avg without (instance, ceph_daemon) (rate(ceph_osd_op_w_latency_sum{ceph_daemon='$osd'}[5m]) / rate(ceph_osd_op_w_latency_count{ceph_daemon='$osd'}[5m]) >= 0)",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "AVG OSD Apply + Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg without (instance, ceph_daemon) (ceph_osd_apply_latency_ms{ceph_daemon='$osd'})",
     "legendFormat": "apply"
    },
    {
     "expr": "avg without (instance, ceph_daemon)(ceph_osd_commit_latency_ms{ceph_daemon='$osd'})",
     "legendFormat": "commit"
    }
   ]
  }
 ]
}
{
 "title": "Ceph - Pools",
 "description": "Ceph Pools dashboard.",
 "tags": [
  "ceph",
  "pools"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "pool",
    "label": "Pool",
    "query": {
     "query": "label_values(ceph_pool_metadata, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pool: $pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pool Storage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum((ceph_pool_max_avail) *on (pool_id) group_left(name)(ceph_pool_metadata{name=~\"^$pool$\"})) by (name)",
     "legendFormat": "Available - {{ name }}"
    },
    {
     "expr": "sum((ceph_pool_stored) *on (pool_id) group_left(name)(ceph_pool_metadata{name=~\"^$pool$\"})) by (name)",
     "legendFormat": "Stored - {{ name }}"
    },
    {
     "expr": "sum((ceph_pool_stored_raw) *on (pool_id) group_left(name)(ceph_pool_metadata{name=~\"^$pool$\"})) by (name)",
     "legendFormat": "Raw - {{ name }}"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, pool_id, name) ((ceph_pool_stored / (ceph_pool_stored + ceph_pool_max_avail)) *on (pool_id) group_left(name)(ceph_pool_metadata{name=~\"^$pool$\"}))"
    }
   ]
  },
  {
   "title": "Pool Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Objects in Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum((ceph_pool_objects) *on (pool_id) group_left(name)(ceph_pool_metadata{name=~\"^$pool$\"})) by (name)",
     "legendFormat": "Objects - {{ name }}"
    },
    {
     "expr": "sum((ceph_pool_dirty) *on (pool_id) group_left(name)(ceph_pool_metadata{name=~\"^$pool$\"})) by (name)",
     "legendFormat": "Dirty Objects - {{ name }}"
    },
    {
     "expr": "sum((ceph_pool_quota_objects) *on (pool_id) group_left(name)(ceph_pool_metadata{name=~\"^$pool$\"})) by (name)",
     "legendFormat": "Quota Objects - {{ name }}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum((irate(ceph_pool_rd[3m])) *on (pool_id) group_left(name)(ceph_pool_metadata{name=~\"^$pool$\"})) by (name)",
     "legendFormat": "Read - {{ name }}"
    },
    {
     "expr": "sum((irate(ceph_pool_wr[3m])) *on (pool_id) group_left(name)(ceph_pool_metadata{name=~\"^$pool$\"})) by (name)",
     "legendFormat": "Write - {{ name }}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum((irate(ceph_pool_rd_bytes[5m])) *on (pool_id) group_left(name)(ceph_pool_metadata{name=~\"^$pool$\"})) by (name)",
     "legendFormat": "Read Bytes - {{ name }}"
    },
    {
     "expr": "sum((irate(ceph_pool_wr_bytes[5m])) *on (pool_id) group_left(name)(ceph_pool_metadata{name=~\"^$pool$\"})) by (name)",
     "legendFormat": "Written Bytes - {{ name }}"
    }
   ]
  }
 ]
}