apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials-es
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: admin-user
      remoteRef:
        key: "a68fefcf-7626-4af6-88d8-b3e300ae914f"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
        nullBytePolicy: Ignore
    - secretKey: admin-password
      remoteRef:
        key: "1cc63b5d-efd2-41ba-8ef2-b3e300aed68e"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
        nullBytePolicy: Ignore
