apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-data-pvc
  namespace: qbittorrent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-app-data
  resources:
    requests:
      storage: 10Gi 
