apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: qbittorrent
  namespace: qbittorrent
  annotations:
    external-dns.alpha.kubernetes.io/hostname: qbittorrent.oliverilp.ee
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  parentRefs:
    - name: traefik-internal-gateway
      namespace: traefik
  hostnames:
    - "qbittorrent.oliverilp.ee"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: qbittorrent
          port: 9092
