entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

service:
  type: LoadBalancer
  spec:
    loadBalancerIP: 10.1.1.101

providers:
  kubernetesGateway:
    enabled: true

gateway:
  enabled: false

gatewayClass:
  enabled: true
  name: traefik-public

ingressClass:
  enabled: false
  isDefaultClass: false

metrics:
  prometheus:
    enabled: true
    service:
      labels:
        gateway-type: public

deployment:
  replicas: 2

podLabels:
  gateway-type: public
  traefik-instance: public

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
              traefik-instance: public
          topologyKey: kubernetes.io/hostname
