apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memos
  namespace: memos
  labels:
    app: memos
spec:
  serviceName: memos
  replicas: 1
  selector:
    matchLabels:
      app: memos
  template:
    metadata:
      labels:
        app: memos
    spec:
      containers:
        - name: memos
          image: neosmemo/memos:0.30.0@sha256:71a5b4738d1bed96e92112004054f0888e92791b64eb78afd79077c96e6f9327
          ports:
            - name: http
              containerPort: 5230
              protocol: TCP
          env:
            - name: MEMOS_PORT
              value: "5230"
            - name: MEMOS_MODE
              value: "prod"
          # - name: MEMOS_DRIVER
          #   value: "postgres"
          # - name: MEMOS_DSN
          #   valueFrom:
          #     secretKeyRef:
          #       name: memos-postgres-auth
          #       key: dsn
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
          volumeMounts:
            - name: memos-data
              mountPath: /var/opt/memos
          livenessProbe:
            httpGet:
              path: /
              port: 5230
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 5230
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: memos-data
          persistentVolumeClaim:
            claimName: memos-data-pvc
