apiVersion: v1
kind: Service
metadata:
  name: memos
  namespace: memos
  labels:
    app: memos
spec:
  selector:
    app: memos
  ports:
  - name: http2
    port: 5230
    targetPort: 5230
    protocol: TCP
    appProtocol: kubernetes.io/h2c
  type: ClusterIP 
