apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-app-data
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: nfs.csi.k8s.io
parameters:
  server: "10.1.1.22"
  share: "/mnt/seagate/k8s"
  subDir: "${pvc.metadata.name}"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4
  - rsize=8192
  - wsize=8192
  - tcp
  - timeo=14
  - noatime
  - hard
  - retrans=2 
