apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-media-pv
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.1.1.22
    path: /mnt/seagate/media
