apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data-local-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
