apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-shared-media-pv
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.1.1.22
    path: /mnt/seagate/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-shared-media-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: jellyfin-shared-media-pv 
