apiVersion: v1
kind: ConfigMap
metadata:
  name: mkv-strip-config
  namespace: mkv-strip
data:
  config.json: |
    {
      "directories": [
        "/media/la-movies",
        "/media/shows"
      ],
      "remove_languages": [
        "rus",
        "ukr",
        "bel"
      ],
      "recursive": true,
      "keep_going": true,
      "in_place": true,
      "dry_run": false,
      "cleanup_leftovers": true,
      "fail_on_file_errors": true,
      "min_output_size_ratio": 0.3
    }
