apiVersion: v1
kind: PersistentVolume
metadata:
  name: mkv-strip-media-pv
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.1.30.10
    path: /mnt/seagate/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mkv-strip-media-pvc
  namespace: mkv-strip
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: mkv-strip-media-pv

