apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
  namespace: emqx
spec:
  image: emqx/emqx:5.10.0

  # Core template with 3 replicas and persistence
  coreTemplate:
    spec:
      replicas: 3
      volumeClaimTemplates:
        storageClassName: nfs-app-data
        resources:
          requests:
            storage: 5Gi
        accessModes:
          - ReadWriteOnce

      env:
        - name: TZ
          value: "Europe/Tallinn"

  # Dashboard service configuration
  dashboardServiceTemplate:
    metadata:
      name: emqx-dashboard
    spec:
      type: ClusterIP
      ports:
        - name: dashboard
          port: 18083
          targetPort: 18083
          protocol: TCP

  # Listeners service configuration
  listenersServiceTemplate:
    metadata:
      name: emqx-listeners
    spec:
      type: ClusterIP
      ports:
        - name: mqtt
          port: 1883
          targetPort: 1883
          protocol: TCP
        - name: mqtts
          port: 8883
          targetPort: 8883
          protocol: TCP
        - name: ws
          port: 8083
          targetPort: 8083
          protocol: TCP
        - name: wss
          port: 8084
          targetPort: 8084
          protocol: TCP
