apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-data
  namespace: linkwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-app-data
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-data
  namespace: linkwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-app-data
  resources:
    requests:
      storage: 2Gi 
