apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-data-pvc
  namespace: linkwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-data-pvc
  namespace: linkwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 2Gi 
