apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden-meilisearch-master-key-es
  namespace: linkwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: linkwarden-meilisearch-master-key
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: key
      remoteRef:
        key: "3f2e4894-51af-4366-8fe8-b31800c82d2f"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
        nullBytePolicy: Ignore
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden-postgres-auth-es
  namespace: linkwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: linkwarden-postgres-auth
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: uri
      remoteRef:
        key: "6e572c0a-c834-47bb-907e-b31800c88fc2"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
        nullBytePolicy: Ignore
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden-app-secrets-es
  namespace: linkwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: linkwarden-app-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: nextauth-secret
      remoteRef:
        key: "aae9baa7-65e8-4b6e-9a54-b31800c8f899"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
        nullBytePolicy: Ignore
    - secretKey: auth-issuer
      remoteRef:
        key: "393752d5-cac2-41ca-b3ef-b31800c91c24"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
        nullBytePolicy: Ignore
    - secretKey: auth-client-id
      remoteRef:
        key: "3fdc55bb-5e01-4b00-b3cc-b31800c94fd9"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
        nullBytePolicy: Ignore
    - secretKey: auth-client-secret
      remoteRef:
        key: "4455d477-9eac-4180-a626-b31800c98fad"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
        nullBytePolicy: Ignore
