apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: meilisearch
  namespace: linkwarden
  labels:
    app: meilisearch
spec:
  serviceName: meilisearch
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.53.1@sha256:8d6643d86d71fad6ad3cba92cde7ccfce9e4d6c384bda67598eb553571c32431
          ports:
            - containerPort: 7700
              name: http
          env:
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: linkwarden-meilisearch-master-key
                  key: key
            - name: MEILI_ENV
              value: "production"
            - name: MEILI_MAX_INDEXING_MEMORY
              value: "256Mb"
          resources:
            requests:
              memory: "256Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
          volumeMounts:
            - name: meilisearch-data
              mountPath: /meili_data
          livenessProbe:
            httpGet:
              path: /health
              port: 7700
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 7700
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: meilisearch-data
          persistentVolumeClaim:
            claimName: meilisearch-data-pvc
