apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-cf-token-es
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: SecretStore
  target:
    name: external-dns-cf-token
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: apiKey
      remoteRef:
        key: "0d926a8b-bd21-4399-8622-b316013282c7"
        property: apiKey
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
