provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: external-dns-cf-token
        key: apiKey

rbac:
  create: true

serviceAccount:
  create: true
  name: external-dns

policy: sync

registry: txt
txtOwnerId: external-dns-homelab

logLevel: info

sources:
  - service
  - ingress
  - gateway-httproute

domainFilters:
  - oliverilp.ee
  - crunchyroll.ee

interval: 1m
triggerLoopOnEvent: true

resources:
  requests:
    cpu: 20m
    memory: 130Mi
  limits:
    memory: 130Mi
