replicaCount: 2
installCRDs: true

bitwarden-sdk-server:
  enabled: true
  certificate:
    secretName: bitwarden-tls-certs

serviceMonitor:
  enabled: true

webhook:
  replicaCount: 2

certController:
  replicaCount: 2
