replicaCount: 2
installCRDs: true

podAnnotations:
  secret.reloader.stakater.com/reload: "bitwarden-tls-certs"

bitwarden-sdk-server:
  enabled: true
  certificate:
    secretName: bitwarden-tls-certs
  podAnnotations:
    secret.reloader.stakater.com/reload: "bitwarden-tls-certs"

serviceMonitor:
  enabled: true

webhook:
  replicaCount: 2

certController:
  replicaCount: 2
