apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: bitwarden-secrets-manager
  namespace: external-secrets
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: external-secrets
        key: ca.crt
      organizationID: cfb621a0-1226-4643-b16e-b30f0127dad0
      projectID: 2f0c3d3f-d9a6-4e41-987f-b30f0128c96b
