crds:
  enabled: true

webhook:
  timeoutSeconds: 30
  serviceType: ClusterIP

# Temporarily disable startupapicheck to avoid hook conflicts
startupapicheck:
  enabled: false

global:
  logLevel: 2
  
  leaderElection:
    namespace: cert-manager
