crds:
  enabled: true

webhook:
  timeoutSeconds: 30
  serviceType: ClusterIP

startupapicheck:
  enabled: true
  timeout: 5m
  backoffLimit: 4

global:
  logLevel: 2
  
  leaderElection:
    namespace: cert-manager
