apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-apps
  namespace: postgresql
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  instances: 3

  managed:
    roles:
      - name: memos
        ensure: present
        comment: "Memos application user"
        login: true
        superuser: false
        createdb: false
        createrole: false
        passwordSecret:
          name: postgres-apps-memos-auth
      - name: linkwarden
        ensure: present
        comment: "Linkwarden application user"
        login: true
        superuser: false
        createdb: false
        createrole: false
        passwordSecret:
          name: postgres-apps-linkwarden-auth
      - name: authentik
        ensure: present
        comment: "Authentik application user"
        login: true
        superuser: false
        createdb: false
        createrole: false
        passwordSecret:
          name: postgres-apps-authentik-auth
      - name: vaultwarden
        ensure: present
        comment: "Vaultwarden application user"
        login: true
        superuser: false
        createdb: false
        createrole: false
        passwordSecret:
          name: postgres-apps-vaultwarden-auth

  superuserSecret:
    name: postgres-apps-superuser-auth

  storage:
    size: 10Gi
    storageClass: nfs-app-data

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
    podAntiAffinityType: preferred
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-apps-superuser-auth-es
  namespace: postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: postgres-apps-superuser-auth
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: "97f7fe1b-e622-4306-9656-b31800d11b72"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
    - secretKey: password
      remoteRef:
        key: "282781b0-c8f2-43c7-b05d-b31800d1418f"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
