apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-apps
  namespace: postgresql
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  instances: 3

  managed:
    roles:
      - name: memos
        ensure: present
        comment: "Memos application user"
        login: true
        superuser: false
        createdb: false
        createrole: false
        passwordSecret:
          name: memos-postgres-credentials
      - name: linkwarden
        ensure: present
        comment: "Linkwarden application user"
        login: true
        superuser: false
        createdb: false
        createrole: false
        passwordSecret:
          name: linkwarden-postgres-credentials
      - name: authentik
        ensure: present
        comment: "Authentik application user"
        login: true
        superuser: false
        createdb: false
        createrole: false
        passwordSecret:
          name: authentik-postgres-credentials

  superuserSecret:
    name: postgres-apps-superuser-credentials

  storage:
    size: 10Gi
    storageClass: nfs-app-data

  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "1"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
    podAntiAffinityType: required
