apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
  labels:
    app: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
      annotations:
        configmap.reloader.stakater.com/reload: "vaultwarden-config"
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.35.7
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: vaultwarden-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-postgres-auth
                  key: database-url
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-app-secrets
                  key: admin-token
                  optional: true
          volumeMounts:
            - name: vaultwarden-data
              mountPath: /data
      volumes:
        - name: vaultwarden-data
          persistentVolumeClaim:
            claimName: vaultwarden-data-pvc
