apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data-pvc
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-app-data
  resources:
    requests:
      storage: 5Gi
