apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-html-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-app-data
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-app-data
  resources:
    requests:
      storage: 200Gi
