apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-admin-credentials-es
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: nextcloud-admin-credentials
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: nextcloud-username
      remoteRef:
        key: "be9c7252-c424-43ef-88ab-b44c00b1dd7d"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
        nullBytePolicy: Ignore
    - secretKey: nextcloud-password
      remoteRef:
        key: "516f456c-a70e-4ec7-8b63-b44c00b1fdc0"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
        nullBytePolicy: Ignore
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-postgres-auth-es
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: nextcloud-postgres-auth
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: "3a793889-8e2c-4552-a427-b44c00b0c219"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
        nullBytePolicy: Ignore
    - secretKey: password
      remoteRef:
        key: "9a943587-1df7-4056-aff5-b44c00b0f452"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
        nullBytePolicy: Ignore
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-redis-auth-es
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: nextcloud-redis-auth
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: password
      remoteRef:
        key: "27b6cdbd-1c92-4aec-b3f3-b44c00b279ec"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
        nullBytePolicy: Ignore
