service:
  type: LoadBalancer
  spec:
    loadBalancerIP: 10.1.1.102

providers:
  kubernetesGateway:
    enabled: true

gateway:
  enabled: true

gatewayClass:
  enabled: false

ingressClass:
  enabled: false
  isDefaultClass: false

metrics:
  prometheus:
    enabled: true
    service:
      labels:
        gateway-type: internal

deployment:
  replicas: 2

podLabels:
  gateway-type: internal
  traefik-instance: internal

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
              traefik-instance: internal
          topologyKey: kubernetes.io/hostname
