apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich-database
  namespace: postgresql
spec:
  cluster:
    name: postgres-immich
  name: immichdb
  owner: immich
  databaseReclaimPolicy: retain
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-immich-auth-es
  namespace: postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: postgres-immich-auth
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: "2b50d212-6109-4371-ba00-b31800d860aa"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
        nullBytePolicy: Ignore
    - secretKey: password
      remoteRef:
        key: "c83391b6-f92e-431e-9c94-b31800d88691"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
        nullBytePolicy: Ignore
