apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: argocd-dragonfly
  namespace: argocd
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: argocd-dragonfly
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 2
  authentication:
    passwordFromSecret:
      key: redis-password
      name: argocd-redis
  resources:
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      cpu: 600m
      memory: 512Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: DoesNotExist
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: dragonfly
        topologyKey: kubernetes.io/hostname
