global:
  domain: argocd.k8s.oliverilp.ee

server:
  replicas: 2
  service:
    type: ClusterIP
  
  extraArgs:
    - --insecure
  
  config:
    url: "https://argocd.k8s.oliverilp.ee"
    application.instanceLabelKey: argocd.argoproj.io/instance
    
    resource.exclusions: |
      - apiGroups:
        - ""
        kinds:
        - Endpoints
        - Event
        clusters:
        - "*"
      - apiGroups:
        - "metrics.k8s.io"
        kinds:
        - "*"
        clusters:
        - "*"

  metrics:
    enabled: true

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

repoServer:
  replicas: 2
  metrics:
    enabled: true

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

controller:
  metrics:
    enabled: true

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

redis:
  enabled: false
redis-ha:
  enabled: false
externalRedis:
  host: argocd-dragonfly.argocd.svc.cluster.local
  port: 6379
  existingSecret: argocd-redis
  existingSecretPasswordKey: redis-password

# Disable dex (OIDC) for now - use admin user
dex:
  enabled: false

# Notifications controller - disabled for now
notifications:
  enabled: false 
