apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  # Ensures cascade delete
spec:
  project: default
  source:
    repoURL: 'git@github.com:oliverilp/homelab.git'  # SSH for private repo
    path: k8s/argocd/applications
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true 
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m 
