apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: argocd-dragonfly
  namespace: argocd
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: argocd-dragonfly
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/managed-by: argocd
spec:
  image: ghcr.io/dragonflydb/dragonfly:v2.0.0@sha256:7426fdb31ddcf7bd9499b4205f36ebaa83b26149ba1609a0d5f8f474b3631233
  replicas: 2
  args:
    - --proactor_threads=1
  authentication:
    passwordFromSecret:
      name: argocd-redis-auth
      key: redis-password
  resources:
    requests:
      cpu: 20m
      memory: 256Mi
    limits:
      memory: 512Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: dragonfly
          topologyKey: kubernetes.io/hostname
