apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-redis-auth-es
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: argocd-redis-auth
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: redis-password
      remoteRef:
        key: "fd83e57d-97af-4831-8dac-b31800e1b179"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
