service:
  type: LoadBalancer
  spec:
    loadBalancerIP: 10.1.1.102

gateway:
  enabled: true

ingressClass:
  enabled: false
  isDefaultClass: false

metrics:
  prometheus:
    enabled: true
    service:
      labels:
        gateway-type: internal

deployment:
  replicas: 2

podLabels:
  gateway-type: internal
  traefik-instance: internal

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
              traefik-instance: internal
          topologyKey: kubernetes.io/hostname

nodeSelector:
  node-role.kubernetes.io/control-plane: "false"
