apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  sources:
    - repoURL: https://charts.rook.io/release
      chart: rook-ceph-cluster
      targetRevision: v1.20.4
      helm:
        releaseName: rook-ceph-cluster
        valueFiles:
          - $values/k8s/rook-ceph/rook-ceph-cluster-values.yaml
    - repoURL: "git@github.com:oliverilp/homelab.git"
      targetRevision: HEAD
      ref: values
    - repoURL: "git@github.com:oliverilp/homelab.git"
      path: k8s/rook-ceph/cluster
      targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
