apiVersion: apps/v1
kind: Deployment
metadata:
  name: librespeed
  namespace: librespeed
  labels:
    app: librespeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librespeed
  template:
    metadata:
      labels:
        app: librespeed
    spec:
      containers:
        - name: librespeed
          image: ghcr.io/librespeed/speedtest:latest@sha256:84708f13755437480579dcc39d05615f41d150921b16c9084a83e702d85f594d
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: MODE
              value: "standalone"
            - name: TELEMETRY
              value: "false"
