apiVersion: apps/v1
kind: Deployment
metadata:
  name: librespeed
  namespace: librespeed
  labels:
    app: librespeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librespeed
  template:
    metadata:
      labels:
        app: librespeed
    spec:
      containers:
        - name: librespeed
          image: ghcr.io/librespeed/speedtest:6.1.0-alpine@sha256:4f3c61fac011476eb486033180155960d490cf340a48c4c13256c417a18088e8
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: MODE
              value: "standalone"
            - name: TELEMETRY
              value: "false"
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              memory: 100Mi
