apiVersion: apps/v1
kind: Deployment
metadata:
  name: librespeed
  namespace: librespeed
  labels:
    app: librespeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librespeed
  template:
    metadata:
      labels:
        app: librespeed
    spec:
      containers:
        - name: librespeed
          image: ghcr.io/librespeed/speedtest:latest@sha256:b24567277adbdf44b8bb536d28c6ec7cb28b2b4f7c79e2932e82c821e84e29d5
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: MODE
              value: "standalone"
            - name: TELEMETRY
              value: "false"
