apiVersion: v1
kind: PersistentVolume
metadata:
  name: stump-shared-manga-pv
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.1.30.10
    path: /mnt/seagate/media/manga
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stump-shared-manga-pvc
  namespace: stump
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: stump-shared-manga-pv
