apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stump-app-secrets-es
  namespace: stump
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: stump-app-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: STUMP_OIDC_CLIENT_ID
      remoteRef:
        key: "61a363d5-f332-4cd7-b10d-b43b00e7cb56"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
        nullBytePolicy: Ignore
    - secretKey: STUMP_OIDC_CLIENT_SECRET
      remoteRef:
        key: "25c808e2-82e2-4b43-ae19-b43b00e7ee6e"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
        nullBytePolicy: Ignore
