apiVersion: v1
kind: ConfigMap
metadata:
  name: stump-config
  namespace: stump
data:
  TZ: "Europe/Tallinn"

  PUID: "0"
  PGID: "0"

  STUMP_CONFIG_DIR: "/config"
  STUMP_PORT: "10801"

  STUMP_OIDC_ENABLED: "true"
  STUMP_OIDC_ISSUER_URL: "https://auth.oliverilp.ee/application/o/stump/"
  STUMP_OIDC_SCOPES: "openid,email,profile"
  STUMP_OIDC_ALLOW_REGISTRATION: "true"
  STUMP_OIDC_DISABLE_LOCAL_AUTH: "true"
