apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: authentik-dragonfly
  namespace: authentik
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: authentik-dragonfly
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: authentik
    app.kubernetes.io/managed-by: authentik
spec:
  replicas: 2
  authentication:
    passwordFromSecret:
      key: redis-password
      name: authentik-redis
  resources:
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      cpu: 600m
      memory: 512Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: dragonfly
          topologyKey: kubernetes.io/hostname
