apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret-key-es
  namespace: authentik
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: authentik-secret-key
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: key
      remoteRef:
        key: "80456ac0-4f0a-4643-9b3e-b31800bbfa10"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-postgres-auth-es
  namespace: authentik
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: authentik-postgres-auth
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: "ec32654c-238e-4f14-94e8-b31800bc3842"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
    - secretKey: password
      remoteRef:
        key: "e66b999f-7782-4bb4-be1f-b31800bc61bc"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-redis-auth-es
  namespace: authentik
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: authentik-redis-auth
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: password
      remoteRef:
        key: "45f43118-7406-45eb-b251-b31800bc9675"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
