apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: authentik-dragonfly
  namespace: authentik
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: authentik-dragonfly
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: authentik
    app.kubernetes.io/managed-by: authentik
spec:
  image: ghcr.io/dragonflydb/dragonfly:v1.38.1@sha256:baf70ba7ad182a992b988497cfa31a488978c8fab7712079784c2401f447e402
  replicas: 2
  authentication:
    passwordFromSecret:
      name: authentik-redis-auth
      key: password
  resources:
    requests:
      cpu: 20m
      memory: 256Mi
    limits:
      memory: 512Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: dragonfly
          topologyKey: kubernetes.io/hostname
