apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: authentik-dragonfly
  namespace: authentik
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: authentik-dragonfly
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: authentik
    app.kubernetes.io/managed-by: authentik
spec:
  image: ghcr.io/dragonflydb/dragonfly:v1.40.2@sha256:18afa43e911f1dff18c7d1eb452361876d9702bb1cdff5c5d75c69617a4065c9
  replicas: 2
  args:
    - --proactor_threads=1
  authentication:
    passwordFromSecret:
      name: authentik-redis-auth
      key: password
  resources:
    requests:
      cpu: 20m
      memory: 256Mi
    limits:
      memory: 512Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: dragonfly
          topologyKey: kubernetes.io/hostname
