authentik:
  # secret_key is now sourced from a Kubernetes secret via environment variable
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to sentry.io, and is fully opt-in
  error_reporting:
    enabled: false
  postgresql:
    name: authentikdb
    user: authentik
    host: postgres-apps-rw.postgresql.svc.cluster.local
  redis:
    host: authentik-dragonfly.authentik.svc.cluster.local

server:
  replicas: 2
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secret-key
          key: key
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-postgres-auth
          key: password
    - name: AUTHENTIK_REDIS__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-redis-auth
          key: password
  ingress:
    enabled: false
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 15
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 15
  resources:
    requests:
      cpu: 20m
      memory: 1200Mi
    limits:
      memory: 1200Mi

worker:
  replicas: 2
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secret-key
          key: key
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-postgres-auth
          key: password
    - name: AUTHENTIK_REDIS__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-redis-auth
          key: password
  resources:
    requests:
      cpu: 50m
      memory: 1300Mi
    limits:
      memory: 1300Mi

postgresql:
  enabled: false
redis:
  enabled: false
