apiVersion: apps/v1
kind: Deployment
metadata:
  name: filestash
  namespace: filestash
  labels:
    app: filestash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filestash
  template:
    metadata:
      labels:
        app: filestash
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-directories
          image: busybox:1.37
          command:
            [
              "sh",
              "-c",
              "mkdir -p /app/data/state/log && chmod -R 775 /app/data/state",
            ]
          volumeMounts:
            - name: filestash-data
              mountPath: /app/data/state
      containers:
        - name: filestash
          image: machines/filestash@sha256:480d53ad14b67a62b21bb4f43a2ea05c345e9e9b6bf2452df3bdcd3c770f81e4
          ports:
            - containerPort: 8334
              name: http
          env:
            - name: APPLICATION_URL
              value: "files.oliverilp.ee"
            - name: CANARY
              value: "true"
          volumeMounts:
            - name: filestash-data
              mountPath: /app/data/state
      volumes:
        - name: filestash-data
          persistentVolumeClaim:
            claimName: filestash-data-pvc
