apiVersion: apps/v1
kind: Deployment
metadata:
  name: filestash
  namespace: filestash
  labels:
    app: filestash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filestash
  template:
    metadata:
      labels:
        app: filestash
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-directories
          image: busybox:1.37
          command:
            [
              "sh",
              "-c",
              "mkdir -p /app/data/state/log && chmod -R 775 /app/data/state",
            ]
          volumeMounts:
            - name: filestash-data
              mountPath: /app/data/state
      containers:
        - name: filestash
          image: machines/filestash@sha256:61743237e5dd2609458a067cc1a8f028ae7d5fe7c42d149dc469edeab34fa2d4
          ports:
            - containerPort: 8334
              name: http
          env:
            - name: APPLICATION_URL
              value: "files.oliverilp.ee"
            - name: CANARY
              value: "true"
          volumeMounts:
            - name: filestash-data
              mountPath: /app/data/state
      volumes:
        - name: filestash-data
          persistentVolumeClaim:
            claimName: filestash-data-pvc
