apiVersion: apps/v1
kind: Deployment
metadata:
  name: filestash
  namespace: filestash
  labels:
    app: filestash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filestash
  template:
    metadata:
      labels:
        app: filestash
    spec:
      containers:
        - name: filestash
          image: machines/filestash@sha256:8517cb254071cd33f0f085d0e2fb278d2748111dc2b16dc4e93029524c1c7e70
          ports:
            - containerPort: 8334
              name: http
          env:
            - name: APPLICATION_URL
              value: "files.oliverilp.ee"
            - name: CANARY
              value: "true"
          volumeMounts:
            - name: filestash-data
              mountPath: /app/data/state
          livenessProbe:
            httpGet:
              path: /
              port: 8334
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8334
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: filestash-data
          persistentVolumeClaim:
            claimName: filestash-data-pvc
