apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app: homeassistant
spec:
  serviceName: homeassistant
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
      annotations:
        configmap.reloader.stakater.com/reload: "homeassistant-config"
    spec:
      containers:
        - name: homeassistant
          image: ghcr.io/home-assistant/home-assistant:2026.5.4
          ports:
            - containerPort: 8123
              name: http
          env:
            - name: TZ
              value: "Europe/Tallinn"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: MQTT_BROKER_URL
              value: "mqtt:1883"
          resources:
            requests:
              cpu: 10m
              memory: 550Mi
            limits:
              memory: 550Mi
          volumeMounts:
            - name: homeassistant-config
              mountPath: /config
            - name: homeassistant-config-file
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
      volumes:
        - name: homeassistant-config
          persistentVolumeClaim:
            claimName: homeassistant-config-pvc
        - name: homeassistant-config-file
          configMap:
            name: homeassistant-config
