apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config-pvc
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-app-data
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data-pvc
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-app-data
  resources:
    requests:
      storage: 1Gi
