apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zigbee2mqtt
  namespace: homeassistant
  labels:
    app: zigbee2mqtt
spec:
  serviceName: zigbee2mqtt
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:2.6.0
          ports:
            - containerPort: 8080
              name: http
      env:
        - name: TZ
          value: "Europe/Tallinn"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
          volumeMounts:
            - name: zigbee2mqtt-data
              mountPath: /app/data
      volumes:
        - name: zigbee2mqtt-data
          persistentVolumeClaim:
            claimName: zigbee2mqtt-data-pvc
