apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgresql
spec:
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:17.5
  instances: 3
  
  managed:
    roles:
    - name: memos
      ensure: present
      comment: "Memos application user"
      login: true
      superuser: false
      createdb: false
      createrole: false
      passwordSecret:
        name: memos-postgres-credentials

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: postgres-credentials

  superuserSecret:
    name: postgres-superuser-credentials

  storage:
    size: 10Gi
    storageClass: nfs-app-data

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"  
      cpu: "1000m"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: DoesNotExist
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            cnpg.io/cluster: postgres
        topologyKey: kubernetes.io/hostname

  monitoring:
    enabled: true 
