apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-s3-credentials-es
  namespace: postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: postgresql-s3-credentials
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: access-key-id
      remoteRef:
        key: "3b0441fb-a677-43a8-8c48-b3dc012bf037"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
        nullBytePolicy: Ignore
    - secretKey: secret-access-key
      remoteRef:
        key: "7c444caa-d1a8-4b17-9c17-b3dc012c1916"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: Fetch
        nullBytePolicy: Ignore
